.authenticate-to-npmjs:
  - &authenticate-to-npmjs |
    echo "$NPM_SCOPE:registry=https://$NPM_REGISTRY_HOST/" >> ~/.npmrc
    echo "//$NPM_REGISTRY_HOST/:_authToken=$NPM_TOKEN" >> ~/.npmrc

before_script:
  - node --version
  - npm --version

stages:
  - build
  - publish

build-8:
  image: node:8-alpine
  stage: build
  script:
    - npm run build

build-10:
  image: node:10-alpine
  stage: build
  script:
    - npm run build

build-12:
  image: node:12-alpine
  stage: build
  script:
    - npm run build

build-14:
  image: node:14-alpine
  stage: build
  script:
    - npm run build

publish:
  stage: publish
  image: node:14.1.0-alpine
  script:
    - *authenticate-to-npmjs
    - export RM_TMP_TAG=cicd-$(date +%s)
    - npm publish --access public --tag $RM_TMP_TAG
    - ./tag-nodejs
  only:
    - /^\d+\.\d+\.\d+(\-[^\.]+\.\d+)?$/
